include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude: 
    - build/**
    - flutter/**
    - lib/core/http/**
  errors:
    invalid_assignment: warning
    missing_return: warning
    dead_code: warning
    todo: warning
    avoid_function_literals_in_foreach_calls: ignore
    missing_required_param: error
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore